# MySQL not yet implemented, will be in future.
use-mysql: false
# Log messages for players who don't own any
default-message: 'default'
# Should the plugin change log messages for default players?
use-default: true
# Give players the default message on join?
give-default-on-join: true