name: LogMessages
version: 0.0.0-SNAPSHOT
author: Spanner
main: com.spanner.logmessages.LogMessages

commands:
  logmessage:
    description: Switch your log message
    aliases: [logmsg,lmsg.logmessages]
    usage: /logmessage <message|givemessage>

permissions:
  logmessages.*:
    descrpition: Gives access to all LogMessages commands (should be admin only!)
    default: op
    children:
      logmessages.switch: true
      logmessages.give: true
  logmessages.switch:
    description: Permits a user to switch their log message
    default: true
  logmessages.give:
    description: Permits an admin to give a player a message type
    default: op